<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ImNotRobot</name>
   <tag></tag>
   <elementGuidId>4eaaf15f-3f69-4b64-86c2-9047d99080d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id = 'recaptcha-anchor-label' and (text() = 'Saya bukan robot' or . = 'Saya bukan robot')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#recaptcha-anchor-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Saya bukan robot&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>990a6dc7-1744-4843-9c1f-b1c59791c033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-anchor-center-item rc-anchor-checkbox-label</value>
      <webElementGuid>ec739345-3288-4009-83b9-655679e85698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>05ff5676-acf2-4487-b485-c3b8ad215cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>88e86f49-0be4-4602-ac72-498a6b2abe4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha-anchor-label</value>
      <webElementGuid>5017974d-79fb-42d7-b51a-d58dad40ea73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saya bukan robot</value>
      <webElementGuid>c5bc7a4b-39ca-4db9-a7d1-f6876c3e4df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-anchor-label&quot;)</value>
      <webElementGuid>ffee7bb3-39f3-4819-a8f2-969fbdfee8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Daftar/iframe_imNotRobot</value>
      <webElementGuid>c0aea379-ea89-4a69-89a8-671069244751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='recaptcha-anchor-label']</value>
      <webElementGuid>37eac6c7-6225-4db1-b135-23b184870e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-anchor-container']/div[3]/div[2]/div/label</value>
      <webElementGuid>ea315177-7df7-4b54-814b-f16e62877529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='reCAPTCHA'])[2]/preceding::label[1]</value>
      <webElementGuid>497c93af-b916-4a71-836e-cb6b00a01b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privasi'])[1]/preceding::label[1]</value>
      <webElementGuid>aa64d185-1d84-406d-b047-69d14c9c46ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saya bukan robot']/parent::*</value>
      <webElementGuid>9d29460a-6490-4676-a7ef-78c66ca33476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>acb0ecee-246f-4466-ae13-8c00781b6b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'recaptcha-anchor-label' and (text() = 'Saya bukan robot' or . = 'Saya bukan robot')]</value>
      <webElementGuid>a5137870-d5f3-4fa9-896f-8023704f4944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
